# Generated by Django 5.1.2 on 2024-11-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_enquiry_created_at_alter_enquiry_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='state',
            field=models.CharField(default='default@example.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='tour_location',
            field=models.CharField(default='default@example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='tour_type',
            field=models.CharField(max_length=50),
        ),
    ]
