# Generated by Django 5.1.2 on 2024-11-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_enquiry_email_enquiry_state_enquiry_tour_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='tour_location',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='tour_type',
            field=models.CharField(max_length=255),
        ),
    ]
