# Generated by Django 5.1.2 on 2024-11-18 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_enquiry_email_remove_enquiry_tour_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='state',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='number_of_persons',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='tour_location',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='travel_date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='tour_type',
            field=models.CharField(max_length=50),
        ),
    ]
