# Generated by Django 5.1.2 on 2024-11-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_enquiry_state_enquiry_number_of_persons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
