# Generated by Django 5.1.2 on 2024-11-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_enquiry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='number_of_persons',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='tour_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='tour_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='travel_date',
            field=models.DateField(),
        ),
    ]
